version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - db
    # sync workspace folder with /go
    volumes:
     - ../../../../.:/go
  db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: gotest
      MYSQL_PASSWORD: gotest
      MYSQL_ROOT_PASSWORD: gotest
      MYSQL_DATABASE: websays
    # sync folders. MySQL data is stored outside container so that rebuilding doesn't clear db.
    # folder is at workspace root.
    volumes:
      - ../../../../_local_mysql_data:/var/lib/mysql